### ISSUE TITLE
findEach breaks with Mongo 3+

### ISSUE THREAD

**Issue by MatejJan** [peerlibrary/meteor-directcollection#3]
Cursor's method `nextObject` has been deprecated in driver 2.x and removed in 3.x so the findEach method now breaks in the line

```
nextObject = blocking(cursor, cursor.nextObject)
```

The method has been renamed to `next` which fixes the bug. For backwards compatibility you can probably just use one or the other.

```
nextObject = blocking(cursor, cursor.next or cursor.nextObject)
```

**Comment by mitar** [comment]
I am pretty sure I use this package and forEach on Mongo 3.4. So not sure. But I can update.
